from . import apartment_details
from . import floor_details
from . import product_template
from . import res_config_settings
from . import res_currency
from . import sale_agent
from . import sale_agent_categories
from . import tower_details
from . import unit_details
from . import unit_reservation
