from . import apartment_details
from . import bulk_price_line
from . import crm_team
from . import floor_details
from . import ihm_agent
from . import multiple_price_type
from . import product_template
from . import res_config_settings
from . import res_currency
from . import res_partner
from . import sale_agent
from . import sale_order
from . import tower_details
from . import unit_activity
from . import unit_details
from . import unit_multiple_price
from . import unit_price_history
from . import unit_reservation
